openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/:
    get:
      operationId: listGetRoutes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/crud/{id}:
    get:
      operationId: retrieveCamisetaCrud
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    post:
      operationId: createCamisetaCrud
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    put:
      operationId: updateCamisetaCrud
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCamisetaCrud
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/camiseta/:
    get:
      operationId: listCamisetas
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Camisetas'
          description: ''
      tags:
      - api
    post:
      operationId: createCamiseta
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camisetas'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Camisetas'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Camisetas'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camisetas'
          description: ''
      tags:
      - api
  /api/camiseta/{id}/:
    get:
      operationId: retrieveCamiseta
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this camiseta.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camisetas'
          description: ''
      tags:
      - api
    put:
      operationId: updateCamiseta
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this camiseta.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camisetas'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Camisetas'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Camisetas'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camisetas'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateCamiseta
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this camiseta.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Camisetas'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Camisetas'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Camisetas'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Camisetas'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyCamiseta
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this camiseta.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/gorras/:
    get:
      operationId: listGorras
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gorrass'
          description: ''
      tags:
      - api
    post:
      operationId: createGorras
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gorrass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Gorrass'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Gorrass'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gorrass'
          description: ''
      tags:
      - api
  /api/gorras/{id}/:
    get:
      operationId: retrieveGorras
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this gorras.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gorrass'
          description: ''
      tags:
      - api
    put:
      operationId: updateGorras
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this gorras.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gorrass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Gorrass'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Gorrass'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gorrass'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateGorras
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this gorras.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Gorrass'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Gorrass'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Gorrass'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gorrass'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyGorras
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this gorras.
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Camisetas:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        main_color:
          type: string
          maxLength: 50
        secondary_color:
          type: string
          maxLength: 50
        brand:
          type: string
          maxLength: 100
        inclusion_date:
          type: string
          format: date
        product_photo_url:
          type: string
          format: uri
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\\
            .(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\\
            ]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1-\uFFFF0-9])?(?:\\\
            .(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
            .?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\s]*)?\\z"
        unit_price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000000
          minimum: -1000000
        current_stock:
          type: integer
          maximum: 9223372036854775807
          format: int64
          minimum: 0
        description:
          type: string
        is_deleted:
          type: boolean
        size_specification:
          enum:
          - MEN
          - WOMEN
          - UNISEX
          type: string
        sleeveless:
          type: boolean
        typo_tejido:
          type: integer
      required:
      - main_color
      - secondary_color
      - brand
      - inclusion_date
      - product_photo_url
      - unit_price
      - current_stock
      - description
      - size_specification
      - sleeveless
    Gorrass:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        main_color:
          type: string
          maxLength: 50
        secondary_color:
          type: string
          maxLength: 50
        brand:
          type: string
          maxLength: 100
        inclusion_date:
          type: string
          format: date
        product_photo_url:
          type: string
          format: uri
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\\
            .(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\\
            ]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1-\uFFFF0-9])?(?:\\\
            .(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
            .?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\s]*)?\\z"
        unit_price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000000
          minimum: -1000000
        current_stock:
          type: integer
          maximum: 9223372036854775807
          format: int64
          minimum: 0
        description:
          type: string
        is_deleted:
          type: boolean
        logo_color:
          type: string
          maxLength: 50
      required:
      - main_color
      - secondary_color
      - brand
      - inclusion_date
      - product_photo_url
      - unit_price
      - current_stock
      - description
      - logo_color
