# Generated by Django 4.2.7 on 2023-11-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_princpal', models.TextField(max_length=50)),
                ('color_segundaria', models.TextField(max_length=50)),
                ('talla', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2Extra Large'), ('3XL', '3Extra large'), ('4XL', '4Extra Large'), ('5XL', '5Extra Large')], max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Hombre', 'H'), ('Mujer', 'M'), ('Unisex', 'U')], max_length=50)),
                ('mangas', models.BooleanField()),
                ('stock_initial', models.IntegerField(editable=False)),
                ('descripcion', models.TextField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Gorras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_princpal', models.TextField(max_length=50)),
                ('color_segundaria', models.TextField(max_length=50)),
                ('color_logo', models.TextField(max_length=50)),
                ('stock_initial', models.IntegerField(editable=False, max_length=99999)),
                ('descripcion', models.TextField(max_length=9999)),
            ],
        ),
    ]
