# Generated by Django 5.0 on 2023-12-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camiseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_specification', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('UNISEX', 'Unisex')], max_length=10)),
                ('sleeveless', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gorras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('inclusion_date', models.DateField()),
                ('product_photo_url', models.URLField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('initial_stock', models.PositiveIntegerField(editable=False)),
                ('current_stock', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('logo_color', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tejido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typo_tejido', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camiseta')),
                ('gorras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gorras')),
            ],
        ),
        migrations.AddField(
            model_name='camiseta',
            name='typo_tejido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tejido'),
        ),
    ]
