# Generated by Django 5.0 on 2023-12-04 19:05

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='brand',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='current_stock',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='description',
            field=models.TextField(default='something'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='inclusion_date',
            field=models.DateField(default=datetime.date(2023, 12, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='initial_stock',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camiseta',
            name='main_color',
            field=models.CharField(default='color', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='product_photo_url',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='secondary_color',
            field=models.CharField(default='blue', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=2.34, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
