# Generated by Django 4.2.7 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('U', 'Unisex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='color_logo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='color_princpal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='color_segundaria',
            field=models.CharField(max_length=50),
        ),
    ]
