# Generated by Django 4.2.7 on 2023-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_camiseta_genero_alter_gorras_color_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta',
            name='talla',
            field=models.CharField(choices=[('2Extra Small', 'XXS'), ('Extra Small', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra Large', 'XL'), ('2Extra Large', 'XXL')], max_length=50),
        ),
    ]
