# Generated by Django 5.0 on 2023-12-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cartitem_camiseta_remove_cartitem_gorras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
