# Generated by Django 4.2.7 on 2023-11-30 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_camiseta_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='gorras',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='color_princpal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='color_segundaria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='stock_initial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='stock_initial',
            field=models.IntegerField(editable=False, max_length=500),
        ),
    ]
