# Generated by Django 4.2.7 on 2023-11-30 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gorras_creado_alter_camiseta_color_princpal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='stock_initial',
            field=models.IntegerField(),
        ),
    ]
