# Generated by Django 4.2.7 on 2023-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_camiseta_creado_alter_gorras_creado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tejido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typo_tejido', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='stock_initial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gorras',
            name='stock_initial',
            field=models.PositiveIntegerField(),
        ),
    ]
