# Generated by Django 4.2.7 on 2023-11-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_camiseta_typo_tejido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camiseta',
            old_name='mangas',
            new_name='con_mangas',
        ),
    ]
