# Generated by Django 4.2.7 on 2023-12-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_camiseta_imagen_gorras_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='camiseta',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gorras',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
