# Generated by Django 4.2.7 on 2023-12-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_camiseta_price_gorras_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camiseta',
            options={'ordering': ['creado']},
        ),
        migrations.AlterModelOptions(
            name='gorras',
            options={'ordering': ['creado']},
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='talla',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camiseta')),
                ('gorras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gorras')),
            ],
        ),
    ]
