# Generated by Django 4.2.7 on 2023-12-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_camiseta_options_alter_gorras_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camiseta',
            old_name='color_princpal',
            new_name='color_principal',
        ),
    ]
